CREATE DATABASE comedor;
USE DATABASE comedor;

CREATE TABLE PERIODO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    FECHAINICIO DATE NOT NULL,
    FECHAFINAL DATE NOT NULL
);

CREATE TABLE ADMINISTRADOR(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CORREO VARCHAR(200) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN NOT NULL
);

CREATE TABLE ESPECIALIDAD(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN NOT NULL
);

CREATE TABLE SECCION(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN NOT NULL
);

CREATE TABLE ESTUDIANTE(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    PRIMERAPELLIDO VARCHAR(200) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR(200) NOT NULL,
    CEDULA VARCHAR(200) NOT NULL,
    IDESPECIALIDAD INT NOT NULL,
    IDSECCION INT NOT NULL,
    ESTADO BOOLEAN
);

CREATE TABLE ASISTENCIA(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDESTUDIANTE INT NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO BOOLEAN
);

ALTER TABLE ASISTENCIA ADD FOREIGN KEY (IDESTUDIANTE) REFERENCES ESTUDIANTE(ID);
ALTER TABLE ESTUDIANTE ADD FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDAD(ID);
ALTER TABLE ESTUDIANTE ADD FOREIGN KEY (IDSECCION) REFERENCES SECCION(ID);
